//! The emit-script harness (design/katsuctl.md §8) — the foundation the
//! `start`/`attach` emit-script commands (§8.3) build on.
//!
//! Two awkward-in-Rust operations — the interactive **attach** (hand a PTY to
//! `ssh`+`tmux`) and the agent **detach** (`setsid` a long-lived qemu) — are
//! handed off to `bash` instead. `katsuctl` performs every probe-dependent
//! *decision* itself (port/CID allocation, branch seed, QMP liveness; §2.2) and
//! then bakes the *results* into a flat, undecorated shell recipe that the
//! devshell wrapper `exec`s.
//!
//! ## The wrapper contract (design §8.1)
//!
//! `katsuctl` writes the recipe to an **anonymous** temp file under
//! `$XDG_RUNTIME_DIR`, prints **only that path** to stdout, and exits 0. On any
//! *planning* failure it writes **nothing**, prints `error:` to stderr, and
//! exits nonzero. The Nix-generated devshell command is therefore a thin wrapper:
//!
//! ```bash
//! # sandbox:start wrapper (generated by Nix; design §9)
//! script="$(katsuctl sandbox --config "$SPEC" start "$@")" || exit
//! exec "${bash}" "$script"
//! ```
//!
//! i.e. katsuctl prints a path; the wrapper `exec`s `bash` on it. A clean stream
//! split makes this robust: stdout is *just* a path, so a planning error is
//! unambiguous (nonzero exit, no path), and `exec` semantics hand the terminal
//! straight to interactive `ssh`+`tmux` (or, in agent mode, detach and return).
//!
//! ## The flat-recipe invariant (design §2.2)
//!
//! **All** branching/looping lives in Rust; the emitted script is a flat recipe
//! with *no* `if`/`case`/retry-loops. Wherever today's shell has a conditional,
//! that decision moves into `katsuctl` and what it emits is unconditional. This
//! module's [`Recipe`] builder reflects that: it offers only a fixed header plus
//! caller-appended **unconditional** lines — there is deliberately no helper for
//! emitting a branch.
//!
//! ## Undecorated output (design §13, ties to [`super::output`])
//!
//! Emitted scripts must stay `exec`-clean, so a recipe is **never** run through a
//! colorizer: [`Recipe::render`] only concatenates the literal lines it was
//! given. The color gating in [`super::output`] governs *human* output; script
//! text bypasses it entirely and carries zero ANSI bytes.
//!
//! Lands ahead of its callers (`start`/`attach` migrate later, design §12), so
//! the surface here reads as `dead_code` until then.
#![allow(dead_code)]

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

use crate::sandbox::host::{Host, Rng};

/// The fixed header every emitted recipe opens with: the `bash` shebang and the
/// strict-mode pragma. Kept as one constant so the golden snapshots pin it.
const HEADER: &str = "#!/usr/bin/env bash\nset -euo pipefail\n";

/// A flat `bash` recipe assembled as text: the fixed [`HEADER`] followed by
/// caller-appended **unconditional** lines (design §2.2, §8.3).
///
/// The builder intentionally exposes no way to emit a conditional or a loop —
/// all branching stays in Rust, and the recipe is a flat, reviewable sequence of
/// literal commands. [`Self::render`] just concatenates those lines, so the
/// output is undecorated by construction (no ANSI ever; design §13).
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Recipe {
    /// Body lines, in append order; the header is prepended at render time.
    lines: Vec<String>,
}

impl Recipe {
    /// A fresh recipe carrying only the header (no body lines yet).
    pub fn new() -> Self {
        Self::default()
    }

    /// Append one unconditional command line. Returns `&mut Self` so calls chain.
    pub fn line(&mut self, line: impl Into<String>) -> &mut Self {
        self.lines.push(line.into());
        self
    }

    /// Append a `# `-prefixed comment line (recipes stay readable/reviewable).
    pub fn comment(&mut self, text: impl AsRef<str>) -> &mut Self {
        self.line(format!("# {}", text.as_ref()))
    }

    /// Append a blank separator line.
    pub fn blank(&mut self) -> &mut Self {
        self.line(String::new())
    }

    /// Whether any body line has been appended (the header is always present).
    pub fn is_empty(&self) -> bool {
        self.lines.is_empty()
    }

    /// Render the full script text: the header, then (when non-empty) a blank
    /// separator and each body line, each newline-terminated. Pure string
    /// concatenation — no colorizer is ever involved, so the result is
    /// `exec`-clean (design §13).
    pub fn render(&self) -> String {
        let mut out = String::from(HEADER);
        if !self.lines.is_empty() {
            out.push('\n');
            for line in &self.lines {
                out.push_str(line);
                out.push('\n');
            }
        }
        out
    }
}

/// Resolve the directory anonymous scripts are written under: `$XDG_RUNTIME_DIR`,
/// falling back to `/tmp` when it is unset or empty — the same
/// `${XDG_RUNTIME_DIR:-/tmp}` rule [`super::spec::resolve_roots`] uses (design
/// §8.1; lib/sandbox/default.nix:1604-1605).
pub fn script_runtime_dir() -> PathBuf {
    runtime_dir_from(|k| std::env::var(k).ok())
}

/// [`script_runtime_dir`] over an injected environment lookup, so the fallback is
/// a pure function testable against a fake env (design §7.2 tier 1).
fn runtime_dir_from(get: impl Fn(&str) -> Option<String>) -> PathBuf {
    match get("XDG_RUNTIME_DIR").filter(|v| !v.is_empty()) {
        Some(dir) => PathBuf::from(dir),
        None => PathBuf::from("/tmp"),
    }
}

/// `mktemp`-style unique path for a script under `dir`. Mixes the pid and two RNG
/// draws so two concurrent `start`s never collide; tests inject a scripted RNG
/// for a deterministic name (design §8.1, "anonymous temp file").
fn temp_script_path(dir: &Path, rng: &mut impl Rng) -> PathBuf {
    let suffix = format!("{:08x}{:08x}", rng.next_u32(), rng.next_u32());
    dir.join(format!(
        "katsuctl-script-{}-{suffix}.sh",
        std::process::id()
    ))
}

/// Write `recipe` to an anonymous temp file under `dir`, returning the path.
///
/// File-writing goes through the [`Host`] seam (design §7.1) so a seam test can
/// assert the exact recipe contents without a real `exec`. The path is unique
/// per [`temp_script_path`]; cleanup is best-effort and not entangled with
/// instance lifecycle (design §8.1).
pub fn write_script(
    host: &dyn Host,
    dir: &Path,
    rng: &mut impl Rng,
    recipe: &Recipe,
) -> Result<PathBuf> {
    let path = temp_script_path(dir, rng);
    host.write(&path, recipe.render().as_bytes())
        .with_context(|| format!("writing emitted script to {}", path.display()))?;
    Ok(path)
}

/// The full emit handoff (design §8.1): run the probe-dependent `plan`, and only
/// if it succeeds write the recipe and print **only** its path to stdout.
///
/// The ordering *is* the contract: planning happens first, so a planning failure
/// short-circuits with `Err` before any file is written — the wrapper sees a
/// nonzero exit and no path, and the caller surfaces the error as `error:` on
/// stderr (design §8.1; the `error:` rendering lives in [`super::output`]).
pub fn emit<F>(host: &dyn Host, dir: &Path, rng: &mut impl Rng, plan: F) -> Result<()>
where
    F: FnOnce() -> Result<Recipe>,
{
    let recipe = plan()?;
    let path = write_script(host, dir, rng, &recipe)?;
    println!("{}", path.display());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::sandbox::host::{Call, FakeHost};

    /// True iff the string carries an ANSI escape (SGR) sequence — mirrors the
    /// `output` module's gating check so "scripts stay undecorated" is enforced.
    fn has_ansi(s: &str) -> bool {
        s.contains('\u{1b}')
    }

    /// A scripted [`Rng`] yielding a fixed sequence, repeating the last value —
    /// keeps the emitted temp-file name deterministic for assertions.
    struct FakeRng {
        values: Vec<u32>,
        next: usize,
    }

    impl FakeRng {
        fn new(values: &[u32]) -> Self {
            Self {
                values: values.to_vec(),
                next: 0,
            }
        }
    }

    impl Rng for FakeRng {
        fn next_u32(&mut self) -> u32 {
            let value = self.values[self.next.min(self.values.len() - 1)];
            self.next += 1;
            value
        }
    }

    /// A trivial, deterministic recipe shared by several tests + the snapshot.
    fn trivial_recipe() -> Recipe {
        let mut recipe = Recipe::new();
        recipe
            .comment("trivial smoke recipe for the emit harness")
            .line(r#"echo "hello from katsuctl""#)
            .blank()
            .line(r#"mkdir -p "/run/example/katsuobushi""#);
        recipe
    }

    // ---- the Recipe builder ----

    #[test]
    fn it_starts_with_the_shebang_and_strict_mode() {
        let recipe = Recipe::new();
        assert_eq!(recipe.render(), "#!/usr/bin/env bash\nset -euo pipefail\n");
        assert!(recipe.is_empty(), "no body lines yet");
    }

    #[test]
    fn it_appends_unconditional_lines_in_order() {
        let mut recipe = Recipe::new();
        recipe.line("first").line("second").line("third");
        let text = recipe.render();
        assert!(text.starts_with("#!/usr/bin/env bash\nset -euo pipefail\n"));
        let body: Vec<&str> = text.lines().skip(2).collect();
        // Header, blank separator, then the three lines in order.
        assert_eq!(body, vec!["", "first", "second", "third"]);
        assert!(!recipe.is_empty());
    }

    #[test]
    fn it_renders_comments_and_blanks() {
        let mut recipe = Recipe::new();
        recipe.comment("note").blank().line("cmd");
        let text = recipe.render();
        assert!(
            text.contains("\n# note\n"),
            "comment is `# `-prefixed: {text}"
        );
        assert!(text.contains("\n\ncmd\n"), "blank separates: {text}");
    }

    #[test]
    fn it_emits_no_ansi_bytes() {
        // The recipe is never run through a colorizer (design §13).
        let text = trivial_recipe().render();
        assert!(
            !has_ansi(&text),
            "emitted script must carry zero ANSI: {text:?}"
        );
    }

    // ---- runtime-dir resolution ----

    #[test]
    fn it_uses_xdg_runtime_dir_when_set() {
        let dir = runtime_dir_from(|k| (k == "XDG_RUNTIME_DIR").then(|| "/run/user/1000".into()));
        assert_eq!(dir, PathBuf::from("/run/user/1000"));
    }

    #[test]
    fn it_falls_back_to_tmp_when_runtime_dir_unset_or_empty() {
        assert_eq!(runtime_dir_from(|_| None), PathBuf::from("/tmp"));
        // Shell `:-` falls back on empty, not just unset.
        assert_eq!(
            runtime_dir_from(|k| (k == "XDG_RUNTIME_DIR").then(String::new)),
            PathBuf::from("/tmp")
        );
    }

    #[test]
    fn it_names_a_unique_dot_sh_path_under_the_dir() {
        let dir = Path::new("/run/user/1000");
        let mut rng = FakeRng::new(&[0xdead_beef, 0x0000_0001]);
        let path = temp_script_path(dir, &mut rng);
        assert!(path.starts_with(dir), "under the runtime dir: {path:?}");
        let name = path.file_name().unwrap().to_str().unwrap();
        assert!(name.starts_with("katsuctl-script-"), "named: {name}");
        assert!(
            name.ends_with("deadbeef00000001.sh"),
            "rng suffix + .sh: {name}"
        );
    }

    // ---- the emit path (seam-level) ----

    #[test]
    fn it_writes_the_recipe_through_the_host_seam() {
        let host = FakeHost::new();
        let dir = Path::new("/run/user/1000");
        let mut rng = FakeRng::new(&[1, 2]);
        let recipe = trivial_recipe();

        let path = write_script(&host, dir, &mut rng, &recipe).expect("write should succeed");

        // Exactly one Write, to the returned path, carrying the rendered recipe.
        assert_eq!(
            host.calls(),
            vec![Call::Write(path.clone(), recipe.render().into_bytes())]
        );
        assert!(path.starts_with(dir));
    }

    #[test]
    fn it_prints_the_path_and_writes_on_a_successful_plan() {
        let host = FakeHost::new();
        let mut rng = FakeRng::new(&[1, 2]);
        emit(&host, Path::new("/run/user/1000"), &mut rng, || {
            Ok(trivial_recipe())
        })
        .expect("emit should succeed");
        // A single Write happened (the path also went to stdout).
        assert!(matches!(host.calls().as_slice(), [Call::Write(_, _)]));
    }

    #[test]
    fn it_writes_nothing_when_planning_fails() {
        // The plan runs first; its failure must short-circuit before any write,
        // so no file is created (design §8.1).
        let host = FakeHost::new();
        let mut rng = FakeRng::new(&[1, 2]);
        let err = emit(&host, Path::new("/run/user/1000"), &mut rng, || {
            anyhow::bail!("simulated planning failure")
        })
        .expect_err("a planning failure must propagate");
        assert!(format!("{err:#}").contains("simulated planning failure"));
        assert!(host.calls().is_empty(), "no write on planning failure");
    }

    // ---- round-trip through the real filesystem + exec ----

    #[test]
    fn it_round_trips_and_is_exec_able() {
        use crate::sandbox::host::HostImpl;

        let host = HostImpl::new().expect("host runtime");
        let dir = std::env::temp_dir().join(format!("katsuctl-emit-it-{}", std::process::id()));
        std::fs::create_dir_all(&dir).expect("scratch dir");
        let mut rng = FakeRng::new(&[0x1111_2222, 0x3333_4444]);

        // A recipe whose body is safe to actually run.
        let mut recipe = Recipe::new();
        recipe
            .comment("round-trip smoke recipe")
            .line("true")
            .line(r#"echo "emit ok" > /dev/null"#);

        let path = write_script(&host, &dir, &mut rng, &recipe).expect("write");

        // write → read back the path's contents == the recipe.
        let read_back = std::fs::read_to_string(&path).expect("read back");
        assert_eq!(read_back, recipe.render(), "round-trips byte-for-byte");

        // exec-able: starts with shebang + strict mode, and no ANSI anywhere.
        assert!(read_back.starts_with("#!/usr/bin/env bash\nset -euo pipefail\n"));
        assert!(!has_ansi(&read_back), "no ANSI bytes in the emitted script");

        // And it really runs cleanly under bash.
        let status = std::process::Command::new("bash")
            .arg(&path)
            .status()
            .expect("bash should run the emitted script");
        assert!(status.success(), "emitted recipe execs cleanly");

        let _ = std::fs::remove_dir_all(&dir);
    }

    // ---- golden snapshot (design §7.2 tier 2) ----

    #[test]
    fn it_snapshots_a_trivial_recipe() {
        // The golden harness #014/#015 reuse: a diff in a generated recipe is a
        // reviewable snapshot failure. Secrets never appear in a snapshot
        // (design §10) — this trivial recipe has none.
        insta::assert_snapshot!(snapshot_recipe(&trivial_recipe()));
    }

    /// Snapshot helper: the exact text a recipe renders to (the bytes that would
    /// be written to the temp file). Shared so the emit-script commands snapshot
    /// their recipes the same way.
    fn snapshot_recipe(recipe: &Recipe) -> String {
        recipe.render()
    }
}
